### ISSUE TITLE
ec2 재부팅해도 fastApi 자동으로 스타트하게 셋업해주세요

### ISSUE THREAD

**Issue by roeniss** [AUSG/achieve-api#1]
systemctl, systemd, supervisor 
같은게 필요할거예요 

(예기치 못한 상황의 재부팅에 대비하기)

ps) mysql도 마찬가지 입니다

**Comment by umi0410** [comment]
이거 @seongbin9786 이가 짠 docker-compose.yml에 restart policy 그대로 쓰면 될 듯해요.

근데 성빈이랑 제가 짠 코드는 아직 로컬에만 있어요 ㅋㅋ

**Comment by roeniss** [comment]
@umi0410 그 설정으로 os 재부팅도 잡을수있어요? ㅇ.ㅇ

1. 도커도 자동으로 부팅되도록 셋업해야 하고,
2. 그렇게 뜬 도커가 죽은 파드들 보고 스타트 걸어줘야 됩니다
이 중 2번이 저 옵션으로 된단 말씀이시죠?

**Comment by umi0410** [comment]
1번은 아마 우분투 도커 까는 순간 자동으로 그렇게 될거구 2번은 파드는 아니고 컨테이너긴한데 그춍 되죠~

**Comment by roeniss** [comment]
우분투군요

**Comment by seongbin9786** [comment]
예기치 못한 재부팅은 생각 못해 본 1인.. 신기하넹용

**Comment by seongbin9786** [comment]
진수님 말씀처럼 데비안과 우분투에선 설치 시 시작 프로그램(?)으로 등록이 된다고 하네용

https://docs.docker.com/engine/install/linux-postinstall/#configure-docker-to-start-on-boot

**Comment by roeniss** [comment]
@seongbin9786 예기치 못한 상황은 ec2에서는 거의 일어나기 힘든 상황이겠네요 ㅎㅎ 보다 현실적인 상황은 서버 강제 재부팅하는 경우일듯요 이럴 때 위 세팅이 안되어있으면 매번 한번씩 접속해서 건드려줘야될거예요
